// Auto-generated by update_portfolio.py - DO NOT EDIT THIS FILE DIRECTLY
// Edit portfolio-config.json and run 'python3 update_portfolio.py' instead.
const portfolioData = [
    {
        "id": "corridor-illustration",
        "title": "Corridor Book Illustration",
        "category": "Illustration",
        "coverUrl": "Corridor Book Illustrations/UC 01.jpg",
        "size": "normal",
        "description": "Created over 120 black-and-white illustrations with grayscale shading for a published horror-themed book. Produced story scenes, environmental illustrations, props, maps, and visual story elements while maintaining a cohesive artistic style and meeting publication deadlines.",
        "videos": [
            {
                "provider": "local",
                "id": "Corridor Book Illustrations/Top Ten Scary Games You Can Play In Your Head, By Yourself.mp4",
                "title": "Scary Games Animatic Process",
                "embed": true
            }
        ],
        "downloads": [],
        "assets": [
            {
                "url": "Corridor Book Illustrations/1.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/2.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/BC 09.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/BL 05.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/BM 01.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/CT 01.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/CT 02.png",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/CT 06.png",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/CT 11.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/DC 18.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/hg5.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/KL 11.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/MH 04.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/SB 02.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/SG 02.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/UC 01.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/UC 03.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/UC 06.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/UC 07.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Book Illustrations/UC 08 v2.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "killermike-cod-video",
        "title": "KillerMike COD video",
        "category": "Storyboards",
        "coverUrl": "KillerMike COD video/1.webp",
        "size": "normal",
        "description": "Storyboard panels outlining intense action sequences and camera movements for the KillerMike Call of Duty promotional music video.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "KillerMike COD video/1.png",
                "caption": ""
            },
            {
                "url": "KillerMike COD video/3.webp",
                "caption": ""
            },
            {
                "url": "KillerMike COD video/4.webp",
                "caption": ""
            },
            {
                "url": "KillerMike COD video/5.webp",
                "caption": ""
            },
            {
                "url": "KillerMike COD video/6.webp",
                "caption": ""
            },
            {
                "url": "KillerMike COD video/7.webp",
                "caption": ""
            },
            {
                "url": "KillerMike COD video/8.webp",
                "caption": ""
            },
            {
                "url": "KillerMike COD video/9.webp",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "dojacat-woman-video",
        "title": "DojaCat Woman Video",
        "category": "Storyboards",
        "coverUrl": "DojaCat Woman Video/1.png",
        "size": "normal",
        "description": "Cinematic visual development and detailed storyboard layout for Doja Cat's music video 'Woman'.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "DojaCat Woman Video/2A.webp",
                "caption": ""
            },
            {
                "url": "DojaCat Woman Video/3A.webp",
                "caption": ""
            },
            {
                "url": "DojaCat Woman Video/4A.webp",
                "caption": ""
            },
            {
                "url": "DojaCat Woman Video/5A.webp",
                "caption": ""
            },
            {
                "url": "DojaCat Woman Video/6A.webp",
                "caption": ""
            },
            {
                "url": "DojaCat Woman Video/7A.webp",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "gwens-music-video",
        "title": "Gwen Stefani - Shake The Snow Globe Music Video",
        "category": "Storyboards",
        "coverUrl": "GwenS Music Video/1a.png",
        "size": "normal",
        "description": "Production storyboards tracking choreography, set locations, and framing for GwenS's music video project.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "GwenS Music Video/1a.png",
                "caption": ""
            },
            {
                "url": "GwenS Music Video/2a.webp",
                "caption": ""
            },
            {
                "url": "GwenS Music Video/3a.webp",
                "caption": ""
            },
            {
                "url": "GwenS Music Video/4a.webp",
                "caption": ""
            },
            {
                "url": "GwenS Music Video/5a.webp",
                "caption": ""
            },
            {
                "url": "GwenS Music Video/6a.webp",
                "caption": ""
            },
            {
                "url": "GwenS Music Video/7a.webp",
                "caption": ""
            },
            {
                "url": "GwenS Music Video/8a.webp",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "alien-harvest",
        "title": "Alien 40th Anniversary Short Film: Harvest",
        "category": "Storyboards",
        "coverUrl": "Alien Harvest/1a.png",
        "size": "normal",
        "description": "Developmenting the visual diversity and building tension with the director for the Alien Harvest project.",
        "videos": [
            {
                "provider": "local",
                "id": "Alien Harvest/Alien 40th Anniversary Short Film： 'Harvest'.mp4",
                "title": "Alien 40th Anniversary Short Film: \"Harvest\"",
                "embed": true
            }
        ],
        "downloads": [],
        "assets": [
            {
                "url": "Alien Harvest/2a.webp",
                "caption": ""
            },
            {
                "url": "Alien Harvest/3a.webp",
                "caption": ""
            },
            {
                "url": "Alien Harvest/4a.webp",
                "caption": ""
            },
            {
                "url": "Alien Harvest/5a.webp",
                "caption": ""
            },
            {
                "url": "Alien Harvest/Screenshot_2026-08-21_15-12-00.png",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "brc-last-cup-commercal",
        "title": "BRC - THE LAST CUP OF COFFEE Commercal",
        "category": "Storyboards",
        "coverUrl": "BRC Last Cup Commercal/1a.png",
        "size": "normal",
        "description": "Cinematic visual development and detailed storyboard layout for the BRC Last Cup commercial.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "BRC Last Cup Commercal/1a.png",
                "caption": ""
            },
            {
                "url": "BRC Last Cup Commercal/2a.webp",
                "caption": ""
            },
            {
                "url": "BRC Last Cup Commercal/3a.webp",
                "caption": ""
            },
            {
                "url": "BRC Last Cup Commercal/4a.webp",
                "caption": ""
            },
            {
                "url": "BRC Last Cup Commercal/5a.webp",
                "caption": ""
            },
            {
                "url": "BRC Last Cup Commercal/11.jpg",
                "caption": ""
            },
            {
                "url": "BRC Last Cup Commercal/12.jpg",
                "caption": ""
            },
            {
                "url": "BRC Last Cup Commercal/13.jpg",
                "caption": ""
            },
            {
                "url": "BRC Last Cup Commercal/14.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "Wiz Khalifa - Peace and Love Music Video",
        "title": "Wiz Khalifa - Peace and Love Music Video",
        "category": "Storyboards",
        "coverUrl": "WizK Music Video/1a.png",
        "size": "normal",
        "description": "Visual board sequences mapping the narrative beats and key performance shots for Wiz Khalifa's music video.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "WizK Music Video/2a.webp",
                "caption": ""
            },
            {
                "url": "WizK Music Video/3a.webp",
                "caption": ""
            },
            {
                "url": "WizK Music Video/4a.webp",
                "caption": ""
            },
            {
                "url": "WizK Music Video/5a.webp",
                "caption": ""
            },
            {
                "url": "WizK Music Video/6a.webp",
                "caption": ""
            },
            {
                "url": "WizK Music Video/7a.webp",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "rocketjump-the-show-hulu",
        "title": "Rocket Jump The Show HULU",
        "category": "Storyboards",
        "coverUrl": "Rocket Jump The Show HULU/1a.jpg",
        "size": "wide",
        "description": "Storyboard panels and action planning for Rocket Jump: The Show on Hulu.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "Rocket Jump The Show HULU/1a.jpg",
                "caption": ""
            },
            {
                "url": "Rocket Jump The Show HULU/RJ1.jpg",
                "caption": ""
            },
            {
                "url": "Rocket Jump The Show HULU/RJ2.jpg",
                "caption": "Rocket Jump Storyboards - Action Sequence A"
            },
            {
                "url": "Rocket Jump The Show HULU/RJ4.jpg",
                "caption": "Rocket Jump Storyboards - Action Sequence B"
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "the-innocent-documentary",
        "title": "The Innocent Man NETFLIX Documentary",
        "category": "Storyboards",
        "coverUrl": "The Innocent Documentary/1a.jpg",
        "size": "normal",
        "description": "Visual storyboards and documentary planning for The Innocent project.",
        "videos": [
            {
                "provider": "local",
                "id": "The Innocent Documentary/The Innocent Man ｜ Official Trailer [HD] ｜ Netflix.mp4",
                "title": "The Innocent Man | Official Trailer",
                "embed": true
            }
        ],
        "downloads": [],
        "assets": [
            {
                "url": "The Innocent Documentary/1a.jpg",
                "caption": ""
            },
            {
                "url": "The Innocent Documentary/FMS92_stoaryboards000.jpg",
                "caption": ""
            },
            {
                "url": "The Innocent Documentary/FMS92_stoaryboards001.jpg",
                "caption": ""
            },
            {
                "url": "The Innocent Documentary/FMS92_stoaryboards002.jpg",
                "caption": ""
            },
            {
                "url": "The Innocent Documentary/FMS92_stoaryboards003.jpg",
                "caption": ""
            },
            {
                "url": "The Innocent Documentary/FMS92_stoaryboards004.jpg",
                "caption": ""
            },
            {
                "url": "The Innocent Documentary/FMS92_stoaryboards005.jpg",
                "caption": ""
            },
            {
                "url": "The Innocent Documentary/FMS92_stoaryboards006.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "animatics",
        "title": "Animatics",
        "category": "Animation & Storyboards",
        "coverUrl": "Animatics/1a.png",
        "size": "normal",
        "description": "Animatic timing studies and visual progression work across sequence tests.",
        "videos": [
            {
                "provider": "local",
                "id": "Animatics/Duncanville_Storyboard_Test_v1.mp4",
                "title": "Duncanville Storyboard Test",
                "embed": true
            },
            {
                "provider": "local",
                "id": "Animatics/Pizza Guy Animatic Process.mp4",
                "title": "Pizza Guy Animatic Process",
                "embed": true
            },
            {
                "provider": "local",
                "id": "Animatics/Sam & Max Cinematic Test.mp4",
                "title": "Sam & Max Cinematic Test",
                "embed": true
            },
            {
                "provider": "local",
                "id": "Animatics/Stopmotioin Super Fight Animatic.mp4",
                "title": "Stopmotion Super Fight Animatic",
                "embed": true
            },
            {
                "provider": "local",
                "id": "Animatics/Ultimates Avengers animatic.mp4",
                "title": "Ultimates Avengers Animatic",
                "embed": true
            }
        ],
        "downloads": [],
        "assets": [
            {
                "url": "Animatics/1a.png",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "brc-black-friday",
        "title": "BRC - Bass Pro Battle Royale Commercial",
        "category": "Graphic Design",
        "coverUrl": "BRC Black Friday/1.webp",
        "size": "normal",
        "description": "Campaign layouts and promotional design work for Black Friday sales assets.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "BRC Black Friday/1.webp",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/1a.png",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/2.webp",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/3.webp",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/4.webp",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/5a.jpg",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/6a.jpg",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/7a.jpg",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/8a.jpg",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/9a.jpg",
                "caption": ""
            },
            {
                "url": "BRC Black Friday/10a.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "corridor-battle-born",
        "title": "Corridor Battleborn Trick Shots",
        "category": "Storyboards",
        "coverUrl": "Corridor Battle Born/1a.png",
        "size": "normal",
        "description": "Storyboard and visual development for the Corridor Battle Born project for Corridor Digital YouTube channel.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "Corridor Battle Born/1a.png",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/2a.webp",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/3a.webp",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/4a.webp",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/5a.webp",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/6a.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/7a.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/8a.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/9a.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Battle Born/10a.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "corridor-dimensions",
        "title": "Corridor Demensions Animation",
        "category": "Concept Art & Storyboards & Animation",
        "coverUrl": "Corridor Demensions/1a.png",
        "size": "normal",
        "description": "Character and environment design visual development for the Corridor Demensions concept project.",
        "videos": [
            {
                "provider": "local",
                "id": "Corridor Demensions/The Final Corridor Dimensions Animation Trailer.mp4",
                "title": "The Final Corridor Dimensions Animation Trailer",
                "embed": true
            }
        ],
        "downloads": [
            {
                "name": "Corridor Dimensions Lookbook (PDF)",
                "url": "Corridor Demensions/CD 4x4.pdf"
            }
        ],
        "assets": [
            {
                "url": "Corridor Demensions/1a.png",
                "caption": ""
            },
            {
                "url": "Corridor Demensions/Corridor Dimensions Charcters studies.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Demensions/Evil D BG v1.jpg",
                "caption": ""
            },
            {
                "url": "Corridor Demensions/Screenshot_2026-08-21_14-50-53.png",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "graphic-design-motion-graphics",
        "title": "Graphic Design & Motion Graphics",
        "category": "Motion Graphics",
        "coverUrl": "Graphic Design & Motion Graphics/Graphic Design.jpg",
        "size": "normal",
        "description": "Poster, motion, and graphic design work spanning brand and promotional pieces.",
        "videos": [
            {
                "provider": "local",
                "id": "Graphic Design & Motion Graphics/Gabriel Peregrino_Motion Graiphics Reel.mp4",
                "title": "Motion Graphics Reel",
                "embed": true
            },
            {
                "provider": "local",
                "id": "Graphic Design & Motion Graphics/GabrielP_Animation trailer.mp4",
                "title": "Animation Trailer",
                "embed": true
            },
            {
                "provider": "local",
                "id": "Graphic Design & Motion Graphics/Guillotine Channel Log Animation.mp4",
                "title": "Guillotine Channel Log Animation",
                "embed": true
            }
        ],
        "downloads": [],
        "assets": [
            {
                "url": "Graphic Design & Motion Graphics/Graphic Design.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "kids-art-animation",
        "title": "Kids Art & Animation",
        "category": "Illustration & Animation",
        "coverUrl": "Kids Art & Animation/1b.png",
        "size": "normal",
        "description": "Illustration and animation work focused on child-friendly visual storytelling and creativity.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "Kids Art & Animation/1b.png",
                "caption": ""
            },
            {
                "url": "Kids Art & Animation/bg1.jpg",
                "caption": ""
            },
            {
                "url": "Kids Art & Animation/bg2.jpg",
                "caption": ""
            },
            {
                "url": "Kids Art & Animation/bg4.jpg",
                "caption": ""
            },
            {
                "url": "Kids Art & Animation/bg5.jpg",
                "caption": ""
            },
            {
                "url": "Kids Art & Animation/bg6.jpg",
                "caption": ""
            },
            {
                "url": "Kids Art & Animation/bg7.jpg",
                "caption": ""
            },
            {
                "url": "Kids Art & Animation/ch1.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "liams-fight-animation",
        "title": "Liam's Fight Animation",
        "category": "Animation & Storyboards",
        "coverUrl": "Liam's Fight Animation/1a.png",
        "size": "normal",
        "description": "Animation and story development for the Liam's Fight project.",
        "videos": [
            {
                "provider": "local",
                "id": "Liam's Fight Animation/Liam's CAR-T Story_ Surviving Advanced B-Cell ALL.mp4",
                "title": "Liam's CAR-T Story: Surviving Advanced B-Cell ALL",
                "embed": true
            }
        ],
        "downloads": [],
        "assets": [
            {
                "url": "Liam's Fight Animation/1a.png",
                "caption": ""
            },
            {
                "url": "Liam's Fight Animation/Liam_s Fight_Page_1.jpg",
                "caption": ""
            },
            {
                "url": "Liam's Fight Animation/Liam_s Fight_Page_2.jpg",
                "caption": ""
            },
            {
                "url": "Liam's Fight Animation/Liam_s Fight_Page_3.jpg",
                "caption": ""
            },
            {
                "url": "Liam's Fight Animation/Liam_s Fight_Page_4.jpg",
                "caption": ""
            },
            {
                "url": "Liam's Fight Animation/Liam_s Fight_Page_5.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "five-nations-comic",
        "title": "5 Nations Comic",
        "category": "Comics & Concept Art",
        "coverUrl": "5 Nations Comic/5N_cover.jpg",
        "size": "wide",
        "description": "The complete 5 Nations Comic collection as comic ment to visualy develop a story and world.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "5 Nations Comic/5N_1_gif.gif",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_2_gif.gif",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch3_Pg1.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch3_Pg2.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch3_Pg3.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch3_Pg4.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch3_Pg5.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch3_Pg6.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch4_Pg1.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch4_Pg2.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch4_Pg3-4.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch4_Pg3.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch4_Pg4.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch4_Pg5.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_Ch4_Pg6.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_cover2.jpg",
                "caption": ""
            },
            {
                "url": "5 Nations Comic/5N_cover.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "chaos-agent-comic",
        "title": "Chaos Agent Comic",
        "category": "Comics",
        "coverUrl": "Chaos  Agent Comic/01.jpg",
        "size": "normal",
        "description": "The complete Chaos Agent Comic personal project.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "Chaos  Agent Comic/01.jpg",
                "caption": ""
            },
            {
                "url": "Chaos  Agent Comic/02.jpg",
                "caption": ""
            },
            {
                "url": "Chaos  Agent Comic/03.jpg",
                "caption": ""
            },
            {
                "url": "Chaos  Agent Comic/04.jpg",
                "caption": ""
            },
            {
                "url": "Chaos  Agent Comic/05.jpg",
                "caption": ""
            },
            {
                "url": "Chaos  Agent Comic/06_art.jpg",
                "caption": ""
            },
            {
                "url": "Chaos  Agent Comic/_1.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "comics",
        "title": "Comics",
        "category": "Comics",
        "coverUrl": "Comics/TC_cover2.jpg",
        "size": "normal",
        "description": "The general Comics folder archive, including additional comic-related artwork and pages.",
        "videos": [],
        "downloads": [],
        "assets": [
            {
                "url": "Comics/1a.png",
                "caption": ""
            },
            {
                "url": "Comics/Pizza-Guy.jpg",
                "caption": ""
            },
            {
                "url": "Comics/Pizza-Guy_1.jpg",
                "caption": ""
            },
            {
                "url": "Comics/Pizza-Guy_2.jpg",
                "caption": ""
            },
            {
                "url": "Comics/Pizza-Guy_3.jpg",
                "caption": ""
            },
            {
                "url": "Comics/Pizza-Guy_4.jpg",
                "caption": ""
            },
            {
                "url": "Comics/TC_cover2.jpg",
                "caption": ""
            },
            {
                "url": "Comics/TC_pg1.jpg",
                "caption": ""
            },
            {
                "url": "Comics/TC_pg2.jpg",
                "caption": ""
            },
            {
                "url": "Comics/TC_pg3.jpg",
                "caption": ""
            },
            {
                "url": "Comics/TC_pg4.jpg",
                "caption": ""
            },
            {
                "url": "Comics/TC_pg5.jpg",
                "caption": ""
            },
            {
                "url": "Comics/TC_pg6.jpg",
                "caption": ""
            },
            {
                "url": "Comics/TC_pg7.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "concept-art",
        "title": "Concept Art",
        "category": "Concept Art",
        "coverUrl": "Concept Art/1a.png",
        "size": "normal",
        "description": "The complete Concept Art folder archive containing environment, character, and illustration studies.",
        "videos": [],
        "downloads": [
            {
                "name": "Character Concept Portfolio (PDF)",
                "url": "Concept Art/Character_concept_portfolio.pdf"
            }
        ],
        "assets": [
            {
                "url": "Concept Art/1a.png",
                "caption": ""
            },
            {
                "url": "Concept Art/photo_09_full.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/Rhino.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/Rim_F.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/Rim_LURA_v1.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/Screenshot_2026-08-21_14-41-09.png",
                "caption": ""
            },
            {
                "url": "Concept Art/The Rim_Kit_v1.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/The_Battle.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/The_Drivebye.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/The_Hunt.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/The_Ruinfall.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/TR.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/Valley_door.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/Valley_farm.jpg",
                "caption": ""
            },
            {
                "url": "Concept Art/Valley_tree.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    },
    {
        "id": "storyboards-folder",
        "title": "Storyboards",
        "category": "Storyboards",
        "coverUrl": "storyboards/1a.png",
        "size": "normal",
        "description": "Other storyboards covering pitch boards, production boards, and visual planning work.",
        "videos": [],
        "downloads": [
            {
                "name": "Storyboard Portfolio 2016 (PDF)",
                "url": "storyboards/Storyboard_Portfolio 2016.pdf"
            },
            {
                "name": "Storyboard Portfolio (PDF)",
                "url": "storyboards/Storyboard_portfolio.pdf"
            }
        ],
        "assets": [
            {
                "url": "storyboards/1a.png",
                "caption": ""
            },
            {
                "url": "storyboards/Chps_boards.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/CoR_Storyboards.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/FMS37_stoaryboards.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/FMS92_stoaryboards.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/JCPstoaryboards_Chat.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/JCPstoaryboards_dinner.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/JCPstoaryboards_Grandma.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/photo_07_full.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/Proto_boards.jpg",
                "caption": ""
            },
            {
                "url": "storyboards/Shape_stoaryboards.jpg",
                "caption": ""
            }
        ],
        "youtubeId": ""
    }
];
