// The portfolioData array is now dynamically loaded from portfolio-data.js,
// which is auto-generated by running update_portfolio.py

const gallery = document.getElementById('gallery');
const filtersContainer = document.getElementById('filters');
const projectOverlay = document.getElementById('project-overlay');

let currentFilter = 'All';
let activeProjectAssets = [];
let currentLightboxIndex = 0;

// Initialize Navigation and Filters
function initFilters() {
    const categorySet = new Set();
    categorySet.add('All');

    portfolioData.forEach(item => {
        if (item.category) {
            const parts = item.category.split('&').map(cat => cat.trim());
            parts.forEach(part => {
                if (part) {
                    categorySet.add(part);
                }
            });
        }
    });

    const categories = Array.from(categorySet);

    categories.forEach(cat => {
        const btn = document.createElement('button');
        btn.className = `filter-btn ${cat === 'All' ? 'active' : ''}`;
        btn.textContent = cat;
        btn.addEventListener('click', () => {
            document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            currentFilter = cat;
            renderGallery();
        });
        filtersContainer.appendChild(btn);
    });
}

// Render Home Grid Gallery
function renderGallery() {
    gallery.innerHTML = '';
    const visibleItems = currentFilter === 'All'
        ? portfolioData
        : portfolioData.filter(item => {
            if (!item.category) return false;
            const parts = item.category.split('&').map(cat => cat.trim());
            return parts.includes(currentFilter);
        });

    visibleItems.forEach((item, index) => {
        const el = document.createElement('div');
        el.className = `gallery-item ${item.size || ''}`;
        el.style.animationDelay = `${(index % 10) * 0.05}s`;

        el.innerHTML = `
            <img src="${item.coverUrl}" alt="${item.title}" loading="lazy">
            <div class="overlay">
                <span>${item.category}</span>
                <h3>${item.title}</h3>
            </div>
        `;

        el.addEventListener('click', () => {
            window.location.hash = `project/${item.id}`;
        });
        gallery.appendChild(el);
    });
}

// Routing Management (SPA Page Views)
function handleRoute() {
    const hash = window.location.hash;
    
    if (hash.startsWith('#project/')) {
        const projectId = hash.replace('#project/', '');
        const project = portfolioData.find(p => p.id === projectId);
        if (project) {
            openProject(project);
            return;
        }
    }
    
    closeProjectView();
}

function parseYouTubeId(raw) {
    if (!raw) return '';

    const idMatch = raw.match(/(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/);
    if (idMatch) {
        return idMatch[1];
    }

    return raw.trim();
}

function getVideoEmbedUrl(video) {
    if (video.provider === 'youtube' && video.id && video.embed !== false) {
        const id = parseYouTubeId(video.id);
        if (!id) return '';

        const params = new URLSearchParams({
            rel: '0',
            modestbranding: '1',
            autoplay: '0'
        });

        return `https://www.youtube.com/embed/${id}?${params.toString()}`;
    }
    return '';
}

function getVideoHref(video) {
    if (video.provider === 'youtube' && video.id) {
        const id = parseYouTubeId(video.id);
        return id ? `https://www.youtube.com/watch?v=${id}` : '';
    }
    return video.url || '';
}

function renderProjectVideos(project) {
    const videoContainer = document.getElementById('project-video-container');
    videoContainer.innerHTML = '';

    const videos = project.videos && project.videos.length > 0
        ? project.videos
        : (project.youtubeId ? [{ provider: 'youtube', id: project.youtubeId, title: 'Video' }] : []);

    if (!videos.length) {
        videoContainer.style.display = 'none';
        return;
    }

    videoContainer.style.display = 'block';
    const isLocalFile = window.location.protocol === 'file:';

    videoContainer.innerHTML = videos.map(video => {
        if (video.provider === 'local') {
            const safeSrc = encodeURI(video.id);
            return `
                <div class="video-block">
                    <div class="video-caption">
                        <svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor" style="color: var(--accent); flex-shrink: 0;">
                            <polygon points="5 3 19 12 5 21 5 3"></polygon>
                        </svg>
                        <span>${video.title || 'Video'}</span>
                    </div>
                    <div class="video-player-frame">
                        <video src="${safeSrc}" controls playsinline preload="metadata"></video>
                    </div>
                </div>
            `;
        }

        const embedUrl = getVideoEmbedUrl(video);
        const title = video.title || 'Video';
        const href = getVideoHref(video);

        if (embedUrl) {
            if (isLocalFile) {
                return `
                    <div class="video-block">
                        <div class="video-caption"><strong>${title}</strong></div>
                        <div class="local-video-placeholder" style="background: #141414; border: 1px solid var(--border); display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 45px 20px; text-align: center; border-radius: 8px;">
                            <svg viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="var(--text-muted)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-bottom: 16px;">
                                <rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect>
                                <line x1="7" y1="2" x2="7" y2="22"></line>
                                <line x1="17" y1="2" x2="17" y2="22"></line>
                                <line x1="2" y1="12" x2="22" y2="12"></line>
                                <line x1="2" y1="7" x2="7" y2="7"></line>
                                <line x1="2" y1="17" x2="7" y2="17"></line>
                                <line x1="17" y1="17" x2="22" y2="17"></line>
                                <line x1="17" y1="7" x2="22" y2="7"></line>
                            </svg>
                            <h4 style="font-size: 1.1rem; font-weight: 700; margin-bottom: 8px; color: var(--text-main);">YouTube Embeds Blocked on Local Files</h4>
                            <p style="font-size: 0.9rem; color: var(--text-muted); max-width: 440px; margin-bottom: 24px; line-height: 1.5;">YouTube does not allow video embeds when opening website files directly from your computer (<code>file://</code> protocol).</p>
                            <div style="display: flex; gap: 12px; flex-wrap: wrap; justify-content: center;">
                                <a href="${href}" target="_blank" rel="noopener" class="btn-download" style="background: var(--accent); border-color: var(--accent); color: white;">Watch on YouTube &rarr;</a>
                            </div>
                        </div>
                    </div>
                `;
            }

            return `
                <div class="video-block">
                    <div class="video-caption"><strong>${title}</strong></div>
                    <div class="video-wrapper">
                        <iframe src="${embedUrl}"
                                title="${title}"
                                frameborder="0"
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                                referrerpolicy="strict-origin-when-cross-origin"
                                allowfullscreen>
                        </iframe>
                    </div>
                    ${href ? `<div class="video-fallback"><a href="${href}" target="_blank" rel="noopener">Watch directly on YouTube</a></div>` : ''}
                </div>
            `;
        }

        return `
            <div class="video-block">
                <div class="video-caption"><strong>${title}</strong></div>
                <div class="video-fallback">This video cannot be embedded. <a href="${href}" target="_blank" rel="noopener">Watch it directly on YouTube</a>.</div>
            </div>
        `;
    }).join('');
}

// Open Project Detail Overlay
function openProject(project) {
    document.getElementById('project-title').textContent = project.title;
    
    const catBadge = document.getElementById('project-category');
    catBadge.textContent = project.category;
    
    document.getElementById('project-description').textContent = project.description;
    
    // Setup Downloads
    const downloadsContainer = document.getElementById('project-downloads');
    downloadsContainer.innerHTML = '';
    if (project.downloads && project.downloads.length > 0) {
        project.downloads.forEach(dl => {
            const link = document.createElement('a');
            link.href = dl.url;
            link.className = 'btn-download';
            link.target = '_blank';
            link.download = '';
            link.innerHTML = `
                <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                    <polyline points="7 10 12 15 17 10"></polyline>
                    <line x1="12" y1="15" x2="12" y2="3"></line>
                </svg>
                ${dl.name}
            `;
            downloadsContainer.appendChild(link);
        });
    }

    // Setup Video Player
    renderProjectVideos(project);

    // Setup Gallery
    const projectGallery = document.getElementById('project-gallery-grid');
    projectGallery.innerHTML = '';
    activeProjectAssets = project.assets || [];

    if (activeProjectAssets.length > 0) {
        activeProjectAssets.forEach((asset, index) => {
            const assetDiv = document.createElement('div');
            assetDiv.className = 'project-gallery-item';
            
            const captionHtml = asset.caption ? `<div class="asset-caption">${asset.caption}</div>` : '';
            assetDiv.innerHTML = `
                <img src="${asset.url}" alt="${asset.caption || project.title}" loading="lazy">
                ${captionHtml}
            `;
            
            assetDiv.addEventListener('click', () => openLightbox(index));
            projectGallery.appendChild(assetDiv);
        });
    }

    // Show overlay
    projectOverlay.classList.add('show');
    document.body.style.overflow = 'hidden';
    
    // Scroll detail content to top
    projectOverlay.scrollTop = 0;
    updateBackToTop();
}

// Close Project View
function closeProjectView() {
    projectOverlay.classList.remove('show');
    updateBackToTop();
    
    // Only restore body overflow if lightbox is not active
    const lightbox = document.getElementById('lightbox');
    if (!lightbox.classList.contains('show')) {
        document.body.style.overflow = 'auto';
    }
}

// Lightbox Modal Logic
const lightbox = document.getElementById('lightbox');
const lbImg = document.getElementById('lightbox-img');
const lbCaption = document.getElementById('lightbox-caption');

function openLightbox(index) {
    if (activeProjectAssets.length === 0) return;
    currentLightboxIndex = index;
    updateLightbox();
    lightbox.classList.add('show');
    document.body.style.overflow = 'hidden';
}

function updateLightbox() {
    const asset = activeProjectAssets[currentLightboxIndex];
    if (asset) {
        lbImg.src = asset.url;
        lbCaption.textContent = asset.caption || '';
    }
}

function closeLightbox() {
    lightbox.classList.remove('show');
    // If project overlay is open, keep body overflow hidden. Otherwise restore to auto.
    if (projectOverlay.classList.contains('show')) {
        document.body.style.overflow = 'hidden';
    } else {
        document.body.style.overflow = 'auto';
    }
}

function nextImage(e) {
    if (e) e.stopPropagation();
    if (activeProjectAssets.length === 0) return;
    currentLightboxIndex = (currentLightboxIndex + 1) % activeProjectAssets.length;
    updateLightbox();
}

function prevImage(e) {
    if (e) e.stopPropagation();
    if (activeProjectAssets.length === 0) return;
    currentLightboxIndex = (currentLightboxIndex - 1 + activeProjectAssets.length) % activeProjectAssets.length;
    updateLightbox();
}

// Event Listeners
document.getElementById('project-close').addEventListener('click', () => {
    window.location.hash = '';
});

// Back to Top Button
const backToTopBtn = document.getElementById('back-to-top');

function updateBackToTop() {
    const isOverlayOpen = projectOverlay.classList.contains('show');
    const scrollPos = isOverlayOpen
        ? projectOverlay.scrollTop
        : (window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0);

    if (scrollPos > 300) {
        backToTopBtn.classList.add('show');
    } else {
        backToTopBtn.classList.remove('show');
    }
}

projectOverlay.addEventListener('scroll', updateBackToTop, { passive: true });
window.addEventListener('scroll', updateBackToTop, { passive: true });

backToTopBtn.addEventListener('click', () => {
    if (projectOverlay.classList.contains('show')) {
        projectOverlay.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    } else {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    }
});

document.getElementById('lightbox-close').addEventListener('click', closeLightbox);
document.getElementById('lightbox-next').addEventListener('click', nextImage);
document.getElementById('lightbox-prev').addEventListener('click', prevImage);

lightbox.addEventListener('click', (e) => {
    if (e.target === lightbox) closeLightbox();
});

document.addEventListener('keydown', (e) => {
    if (lightbox.classList.contains('show')) {
        if (e.key === 'Escape') closeLightbox();
        if (e.key === 'ArrowRight') nextImage();
        if (e.key === 'ArrowLeft') prevImage();
    } else if (projectOverlay.classList.contains('show')) {
        if (e.key === 'Escape') window.location.hash = '';
    }
});

// Watch Routing Events
window.addEventListener('hashchange', handleRoute);

// Initialize application
initFilters();
renderGallery();
handleRoute();
